# Generated by Django 3.0.14 on 2023-10-11 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0002_auto_20231010_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='UserName',
        ),
        migrations.AddField(
            model_name='user',
            name='Address',
            field=models.CharField(default=111111, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='WorkHours',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
    ]
